spring:
  data:
    mongodb:
      host: 172.18.115.21
      port: 27017
      database: UserFigure

swagger:
  base-package: com.lingyi.base.userfigure.controllers
  title: 用户画像存储接口
  description: 只负责用户画像的页面展示接口