#spring:
#  data:
#    elasticsearch:
#      cluster-name: lyworkcluster

#      cluster-nodes: http://192.168.16.202:9200
#      cluster-nodes: 172.18.113.84:9300,172.18.113.93:9200,172.18.113.96:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log #elasticsearch日志存储目录
#          data: ./elasticsearch/data #elasticsearch数据存储目录



elasticsearch:
 clustername: elasticsearch
 host: 192.168.16.202
 port: 9300