/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dingxiang.userservicedriver;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AgentType implements org.apache.thrift.TEnum {
  CommonUser(0),
  AgentFirst(1),
  AgentSecond(2),
  AgentThird(3),
  ServiceFirst(4),
  ServiceSecond(5),
  ServiceThird(6);

  private final int value;

  private AgentType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AgentType findByValue(int value) { 
    switch (value) {
      case 0:
        return CommonUser;
      case 1:
        return AgentFirst;
      case 2:
        return AgentSecond;
      case 3:
        return AgentThird;
      case 4:
        return ServiceFirst;
      case 5:
        return ServiceSecond;
      case 6:
        return ServiceThird;
      default:
        return null;
    }
  }
}
