/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dingxiang.userservicedriver;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GetUserPartInfoStatus implements org.apache.thrift.TEnum {
  Success(0),
  InvalidAccount(1),
  NoExist(2);

  private final int value;

  private GetUserPartInfoStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GetUserPartInfoStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Success;
      case 1:
        return InvalidAccount;
      case 2:
        return NoExist;
      default:
        return null;
    }
  }
}
