package cicada.authorization.config; /**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CreateSessionStatus implements TEnum {
  Success(0),
  InvalidUserId(1);

  private final int value;

  private CreateSessionStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CreateSessionStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Success;
      case 1:
        return InvalidUserId;
      default:
        return null;
    }
  }
}
